"""add suppliers

Revision ID: 511491de5dbd
Revises: e07f06e9f37b
Create Date: 2026-06-01 04:45:11.652079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511491de5dbd'
down_revision = 'e07f06e9f37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=False),
    sa.Column('logo', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_email'), ['email'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('supplier')
        batch_op.drop_column('unit')
        batch_op.drop_column('threshold')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('supplier_contact')
        batch_op.drop_column('on_the_way')
        batch_op.drop_column('opening_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('on_the_way', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('supplier_contact', sa.VARCHAR(length=40), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('threshold', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=40), server_default=sa.text("'Packets'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_email'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
