"""add product fields

Revision ID: e07f06e9f37b
Revises: 68a4d3e809d3
Create Date: 2026-05-31 21:29:38.125693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07f06e9f37b'
down_revision = '68a4d3e809d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('category', sa.String(length=80), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('unit', sa.String(length=40), nullable=False, server_default='Packets')
        )
        batch_op.add_column(
            sa.Column('threshold', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column('supplier', sa.String(length=120), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('supplier_contact', sa.String(length=40), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('opening_stock', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('on_the_way', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('on_the_way')
        batch_op.drop_column('opening_stock')
        batch_op.drop_column('supplier_contact')
        batch_op.drop_column('supplier')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('threshold')
        batch_op.drop_column('unit')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
